version: '1'
environments:
  production:
    secrets:
      - name: NODE_ENV
        value: "production"
services:
  web:
    image: node
    env:
      PORT: 3000
    command: npm start
    ports:
      - 3000:3000